name: taggira
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Firebase setups
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  # state management
  flutter_bloc: ^8.1.0
  # auto genirate
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  # Simple direct Service Locator
  get_it: ^7.6.0
  # deal with internationalized/localized messages, date and number formatting
  intl: ^0.19.0
  # in-app localization with map data.
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  #A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^15.0.0
  #otp
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  #UI ---> splash screen , app icon , responsive , bottom navigation bar , lottie , slider
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.6.0
  persistent_bottom_nav_bar: any
  carousel_slider: ^5.0.0
  lottie:

  # selecting images from the Android and iOS image library, and taking new pictures with the camera
  image_picker: ^1.1.2
  # create the uniqe id 
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: 2.5.8
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/
  fonts:
    - family: SeymourOne
      fonts:
        - asset: assets/fonts/SeymourOne/SeymourOne-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf

          weight: 700
          style: italic

flutter_intl:
  enabled: true
