// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsGCKx6oOjQ4FTE343lZsHUi3rf1n1Qeg',
    appId: '1:604631064676:android:b34d193c7a1326bd973f71',
    messagingSenderId: '604631064676',
    projectId: 'isaga-f9d50',
    databaseURL: 'https://isaga-f9d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isaga-f9d50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_6En2WnEL17_S5dRyNPlNSbXiAtnlEKU',
    appId: '1:604631064676:ios:427f5c77e0e8f7e0973f71',
    messagingSenderId: '604631064676',
    projectId: 'isaga-f9d50',
    databaseURL: 'https://isaga-f9d50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isaga-f9d50.appspot.com',
    androidClientId: '604631064676-sgec5g80lbsme1ejiongfe7l83c5o5g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taggira',
  );
}
